version: '3.8'

services:
  mysql:
    container_name: ${DOCKER_APP_NAME}-mysql
    image: arm64v8/mysql:8.3
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    networks:
      - app-network
    restart: unless-stopped

  app:
    build:
      context: '.'
      dockerfile: ./docker/php/Dockerfile
    container_name: ${DOCKER_APP_NAME}-app
    image: ${DOCKER_APP_NAME}-app
    ports:
      - ${DOCKER_PHP_PORT}:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_ROOT_USER}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./web:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  redis:
    image: arm64v8/redis:latest
    container_name: ${DOCKER_APP_NAME}-redis
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    volumes:
      - './docker/redis:/data'
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge
    external: false
